apiVersion: v2
name: spire-crds
description: A Helm chart for Spire CRDs
sources:
  - https://github.com/nais/helm-charts/tree/main/features/spire-crds
  - https://github.com/spiffe/helm-charts-hardened/tree/main/charts/spire-crds
type: application
version: 0.1.0

dependencies:
  - name: spire-crds
    version: "0.5.0"
    repository: "https://spiffe.github.io/helm-charts-hardened/"
