server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    socket_path = "/tmp/spire-server/private/api.sock"
    data_dir = "/opt/spire/data/server"
    log_level = "DEBUG"
    ca_ttl = "24h"
    ca_key_type = "rsa-2048"
    ca_subject = {
        common_name = "spire.example.nais.io"
        country = ["NO"]
        organization = ["nais"]
    }
    default_jwt_svid_ttl = "1h"
    default_x509_svid_ttl = "4h"
    jwt_issuer = "spire.example.nais.io"
    log_format = "text"
    trust_domain = "example.nais.io"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/opt/spire/data/server/datastore.sqlite3"
        }
    }
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "memory" {
        plugin_data = {}
    }
}
