---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-workload
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-workload
  labels:
    app: example-workload
spec:
  selector:
    matchLabels:
      app: example-workload
  template:
    metadata:
      labels:
        app: example-workload
    spec:
      containers:
        - name: example-workload
          image: ghcr.io/spiffe/spire-agent:1.5.1
          command: [ "/opt/spire/bin/spire-agent" ]
          args: [ "api", "watch",  "-socketPath", "/spiffe-workload-api/spire-agent.sock" ]
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
      serviceAccountName: example-workload
